---
- name: Install docker credential helper
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: chouseknecht.install-docker-credential-helper
      docker_repo: docker/docker-credential-helpers
      docker_github_url: https://api.github.com/repos
      docker_release_tag_name: ""
      docker_bin_dest: /usr/local/bin
