# get_ms_assets.yml

- name: Get the tagged release
  uri:
    url: "{{ docker_github_url }}/{{ docker_repo }}/releases/tags/{{ docker_release_tag_name }}"
  register: release
  when: docker_release_tag_name != '' 

- name: Set release
  set_fact:
    assets_url: "{{ release.json.assets_url }}"
  when: docker_release_tag_name != '' 

- name: Get the latest release
  uri:
    url: "{{ docker_github_url }}/{{ docker_repo }}/releases/latest"
  register: release
  when: docker_release_tag_name == '' 

- name: Set release
  set_fact:
    assets_url: "{{ release.json.assets_url }}"
  when: docker_release_tag_name == '' 

- name: Should have an assets_url
  assert:
    that: assets_url is defined

- name: debug
  debug:
    var: assets_url

- name: Get the list of assets
  uri:
    url: "{{ assets_url }}"
  register: assets

