apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ minishift_volume['name'] }}
spec:
  capacity:
    storage: {{ minishift_volume['size'] }}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle 
  hostPath:
    path: {{ minishift_volume['path'] }}
